package com.dh.labdynamo.taskmaster;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Objects;
import java.util.UUID;

@DynamoDBTable(tableName = "tasks")
public class Task {
    private UUID id;
    private String title;
    private String description;
    private String status;
    private String assignee;

    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Task() {}

    public Task(String title, String description) {
        this.title = title;
        this.description = description;
        this.status = "Available";
        this.assignee = "Admin";
    }

    public Task(String title, String description, String assignee){
        this.title = title;
        this.description = description;
        // Check string if null: https://stackoverflow.com/questions/49295291/best-method-to-check-if-a-value-of-a-string-is-null-in-java
        this.status = Objects.equals(null,assignee) ? "Available" : "Assigned";
        this.assignee = assignee;
    }

}
